### PR TITLE
Feat /  Always call the render left/right control functions

### PR DESCRIPTION
**Pull request by langemike**
For accessibility reasons, it is better to always call the render (left/right) controls function and leave the implementation details to the developer. With this change, it's the developer's responsibility to hide or disable the control based on the `disabled` argument.

When the control function returns a falsy value, the control wrapper won't get rendered. Preventing an unneeded `<div />` wrapper.

⚠️ I removed the `hasSlideBefore` state, which always evaluates to `false`, causing the left control to be disabled when you have reached the end of the slider (when using cycle-mode `stop`). I did some (mobile) swipe tests with `console.log` on the state, but I have never seen this being evaluated as `true`. I don't know which problem this variable tries to solve. Please be aware of this while reviewing.

Ticket: https://videodock.atlassian.net/browse/DDSB-4967

### CODE REVIEW

**Review by royschut — COMMENTED** [review]
I think `hasSlideBefore` is not meant for `cycleMode=="stop"`, but for the other cycle modes. Its intention is to disable the leftControl initially, until the slider was used before, so that you don't start the wrong way. 

Maybe we could keep it and use it for `leftControlDisabled`: 

```javascript
const leftControlDisabled = (cycleMode === 'stop' && state.index === 0) || !hasSlideBefore`
```

I think it remains `false`, because it is missing on L194:
```javascript
setState((state) => ({ ...state, toIndex: index, fromIndex: state.index, sliding: true, hasSlideBefore: true }));
```

**Review by ChristiaanScheermeijer — APPROVED** [review]
lgtm!

**Comment by langemike** [comment]
> I think hasSlideBefore is not meant for cycleMode=="stop", but for the other cycle modes. Its intention is to disable the leftControl initially, until the slider was used before, so that you don't start the wrong way.

I understand the reasoning behind it now. But I think it's a bit opinionated to disable the control it on first instance and enable it afterwards.

It was missing on L219 though and not on L194. Because it needs to toggle _after_ sliding.

Do you agree we keep it removed @royschut ?

This implementation detail can also be done by the developer by using the TileSlider `onSlideEnd` prop and making a custom (local) `hasSlideBefore` state to disable the (left) control. That is easier done for the developer, than undoing this logic, because then you need to write your own disable logic (repeating ` (cycleMode === 'stop' && state.index === 0)`). I rather keep the TileSlider "dumb".

**Comment by royschut** [comment]
> Do you agree we keep it removed @royschut ?

Yes, you're right, we can handle it from the implementation if needed!

**Review by royschut — APPROVED** [review]

**Pull request merged**
